# Generated by Django 2.0.7 on 2019-05-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
