# Generated by Django 2.0.7 on 2019-05-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_posts_pub_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
