# Generated by Django 2.0.7 on 2019-05-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20190508_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.TextField(unique='true'),
        ),
    ]
